orbs:
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.2.1

version: 2.1

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./api
          region: AWS_REGION
          repo: airquality
          skip-when-tags-exist: false
          tag: "$CIRCLE_SHA1"
      - aws-ecs/run-task:
          requires:
            - aws-ecr/build-and-push-image
          capacity-provider-strategy: >-
            capacityProvider=FARGATE,weight=1
            capacityProvider=FARGATE_SPOT,weight=1
          cluster: airquality-cluster
          launch-type: ''
          subnet-ids: 'subnet-0cec0e08d01205883,subnet-01b0f0cb387883676'
          task-definition: airquality-task:2